name: disk-util 
base: core18
version: '0.1'
summary: Example disk utility application
description: |
  Example utility to demonstrate accessing USB disks.

grade: stable
confinement: strict

apps:
    list:
      command: bin/list
      plugs:
       - hardware-observe
       - block-devices

    create-format:
      command: bin/format
      plugs:
       - udisks2
       - hardware-observe
       - block-devices

    create:
      command: bin/create
      plugs:
        - udisks2
        - hardware-observe
        - block-devices

    delete:
      command: bin/delete
      plugs:
        - udisks2
        - hardware-observe
        - block-devices

    fdisk:
      command: sbin/fdisk
      plugs:
       - hardware-observe
       - block-devices


parts:
  utility:
    plugin: nil
    stage-packages:
      - util-linux
      - e2fsprogs
      - udisks2

  bin:
    plugin: dump
    source: bin
    organize:
      "*": /bin/

  application:
    plugin: go
    go-importpath: github.com/slimjim777/disk-util
    source: .
    source-type: git
    build-packages:
      - gcc