name: disk-util 
base: core18
version: '0.1'
summary: Example disk utility application
description: |
  Example utility to demonstrate accessing USB disks.

grade: stable
confinement: strict



slots:
  udisks2-svc:
    bus: system
    interface: dbus
    name: org.freedesktop.UDisks2

plugs:
  udisks2-cons:
    bus: system
    interface: dbus
    name: org.freedesktop.UDisks2

apps:
    list:
      command: bin/list
      plugs:
       - hardware-observe
       - block-devices

    format:
      command: bin/format
      plugs:
       - udisks2
       - hardware-observe
       - block-devices
       - udisks2-cons

    fdisk:
      command: sbin/fdisk
      plugs:
       - hardware-observe
       - block-devices


parts:
  utility:
    plugin: nil
    stage-packages:
      - util-linux
      - e2fsprogs
      - udisks2

  bin:
    plugin: dump
    source: bin
    organize:
      "*": /bin/

